name: SCA Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sca-scan:
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create reports directory
      run: mkdir -p reports
    
    - name: Run pip-audit
      run: |
        pip install pip-audit
        pip-audit --format=json --output=reports/pip-audit-report.json || true
    
    - name: Run Safety
      run: |
        pip install safety
        safety check --json --output reports/safety-report.json || true
    
    - name: Parse Reports
      run: python scripts/parse_reports.py
    
    - name: Generate Summary
      run: python scripts/generate_security_summary.py
    
    - name: Upload Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: sca-reports
        path: |
          reports/*.json
          reports/*.txt
        retention-days: 30